Spring security
solsebas/ProjectSupport pull request #18
Opened 2023-05-10 17:48 UTC by xPalka

Dodanie guard do angulara

2023-05-10 18:36 UTC, solsebas requested changes

2023-05-10 18:36 UTC, solsebas commented on src/main/java/pl/polsl/projectsupport/controller/StudentController.java
>      //public List<SupervisorDto> getSupervisors(){ return supervisorService.getSupervisorDtos();}
to by wypadało wyrzucić w końcu

2023-05-10 18:36 UTC, solsebas commented on src/main/java/pl/polsl/projectsupport/controller/TopicController.java
> +    public List<TopicDto> getTopics(){ return topicService.getTopicDtos();}
w końcu topic w dobrym kontrolerze <3

2023-05-10 18:36 UTC, solsebas commented on src/main/java/pl/polsl/projectsupport/controller/TopicController.java
> +    @PostMapping("/topics/add")
boli mnie jakoś to add

2023-05-10 18:36 UTC, solsebas commented on src/main/resources/db/migration/V2__insertData.sql
> +-- INSERT INTO public.user_roles(role_id) VALUES (1); -- USERS_ROLES_ID 6
nie chce mi się drugi raz usuwać :P

2023-05-10 18:36 UTC, solsebas commented on src/main/resources/application.properties
> +#spring.flyway.locations=classpath:db/migration
i tu też nie chce mi się usuwać

2023-05-11 12:06 UTC, xPalka reviewed
poprawione

2023-05-11 12:08 UTC, solsebas approved these changes

2023-05-11 12:09 UTC, merged